/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.changeset.baseline.service.base;

import aQute.bnd.annotation.ProviderType;

import com.liferay.changeset.baseline.model.BaselineInformation;
import com.liferay.changeset.baseline.service.BaselineInformationLocalService;
import com.liferay.changeset.baseline.service.persistence.BaselineEntryPersistence;
import com.liferay.changeset.baseline.service.persistence.BaselineInformationPersistence;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalServiceRegistry;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the baseline information local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.changeset.baseline.service.impl.BaselineInformationLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.changeset.baseline.service.impl.BaselineInformationLocalServiceImpl
 * @see com.liferay.changeset.baseline.service.BaselineInformationLocalServiceUtil
 * @generated
 */
@ProviderType
public abstract class BaselineInformationLocalServiceBaseImpl
	extends BaseLocalServiceImpl implements BaselineInformationLocalService,
		IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.liferay.changeset.baseline.service.BaselineInformationLocalServiceUtil} to access the baseline information local service.
	 */

	/**
	 * Adds the baseline information to the database. Also notifies the appropriate model listeners.
	 *
	 * @param baselineInformation the baseline information
	 * @return the baseline information that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public BaselineInformation addBaselineInformation(
		BaselineInformation baselineInformation) {
		baselineInformation.setNew(true);

		return baselineInformationPersistence.update(baselineInformation);
	}

	/**
	 * Creates a new baseline information with the primary key. Does not add the baseline information to the database.
	 *
	 * @param baselineInformationId the primary key for the new baseline information
	 * @return the new baseline information
	 */
	@Override
	@Transactional(enabled = false)
	public BaselineInformation createBaselineInformation(
		long baselineInformationId) {
		return baselineInformationPersistence.create(baselineInformationId);
	}

	/**
	 * Deletes the baseline information with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param baselineInformationId the primary key of the baseline information
	 * @return the baseline information that was removed
	 * @throws PortalException if a baseline information with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public BaselineInformation deleteBaselineInformation(
		long baselineInformationId) throws PortalException {
		return baselineInformationPersistence.remove(baselineInformationId);
	}

	/**
	 * Deletes the baseline information from the database. Also notifies the appropriate model listeners.
	 *
	 * @param baselineInformation the baseline information
	 * @return the baseline information that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public BaselineInformation deleteBaselineInformation(
		BaselineInformation baselineInformation) {
		return baselineInformationPersistence.remove(baselineInformation);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(BaselineInformation.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return baselineInformationPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.liferay.changeset.baseline.model.impl.BaselineInformationModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end) {
		return baselineInformationPersistence.findWithDynamicQuery(dynamicQuery,
			start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.liferay.changeset.baseline.model.impl.BaselineInformationModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end, OrderByComparator<T> orderByComparator) {
		return baselineInformationPersistence.findWithDynamicQuery(dynamicQuery,
			start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return baselineInformationPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery,
		Projection projection) {
		return baselineInformationPersistence.countWithDynamicQuery(dynamicQuery,
			projection);
	}

	@Override
	public BaselineInformation fetchBaselineInformation(
		long baselineInformationId) {
		return baselineInformationPersistence.fetchByPrimaryKey(baselineInformationId);
	}

	/**
	 * Returns the baseline information with the primary key.
	 *
	 * @param baselineInformationId the primary key of the baseline information
	 * @return the baseline information
	 * @throws PortalException if a baseline information with the primary key could not be found
	 */
	@Override
	public BaselineInformation getBaselineInformation(
		long baselineInformationId) throws PortalException {
		return baselineInformationPersistence.findByPrimaryKey(baselineInformationId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery = new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(baselineInformationLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(BaselineInformation.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"baselineInformationId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery getIndexableActionableDynamicQuery() {
		IndexableActionableDynamicQuery indexableActionableDynamicQuery = new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(baselineInformationLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(BaselineInformation.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"baselineInformationId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {
		actionableDynamicQuery.setBaseLocalService(baselineInformationLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(BaselineInformation.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"baselineInformationId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {
		return baselineInformationLocalService.deleteBaselineInformation((BaselineInformation)persistedModel);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {
		return baselineInformationPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the baseline informations.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.liferay.changeset.baseline.model.impl.BaselineInformationModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of baseline informations
	 * @param end the upper bound of the range of baseline informations (not inclusive)
	 * @return the range of baseline informations
	 */
	@Override
	public List<BaselineInformation> getBaselineInformations(int start, int end) {
		return baselineInformationPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of baseline informations.
	 *
	 * @return the number of baseline informations
	 */
	@Override
	public int getBaselineInformationsCount() {
		return baselineInformationPersistence.countAll();
	}

	/**
	 * Updates the baseline information in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param baselineInformation the baseline information
	 * @return the baseline information that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public BaselineInformation updateBaselineInformation(
		BaselineInformation baselineInformation) {
		return baselineInformationPersistence.update(baselineInformation);
	}

	/**
	 * Returns the baseline entry local service.
	 *
	 * @return the baseline entry local service
	 */
	public com.liferay.changeset.baseline.service.BaselineEntryLocalService getBaselineEntryLocalService() {
		return baselineEntryLocalService;
	}

	/**
	 * Sets the baseline entry local service.
	 *
	 * @param baselineEntryLocalService the baseline entry local service
	 */
	public void setBaselineEntryLocalService(
		com.liferay.changeset.baseline.service.BaselineEntryLocalService baselineEntryLocalService) {
		this.baselineEntryLocalService = baselineEntryLocalService;
	}

	/**
	 * Returns the baseline entry persistence.
	 *
	 * @return the baseline entry persistence
	 */
	public BaselineEntryPersistence getBaselineEntryPersistence() {
		return baselineEntryPersistence;
	}

	/**
	 * Sets the baseline entry persistence.
	 *
	 * @param baselineEntryPersistence the baseline entry persistence
	 */
	public void setBaselineEntryPersistence(
		BaselineEntryPersistence baselineEntryPersistence) {
		this.baselineEntryPersistence = baselineEntryPersistence;
	}

	/**
	 * Returns the baseline information local service.
	 *
	 * @return the baseline information local service
	 */
	public BaselineInformationLocalService getBaselineInformationLocalService() {
		return baselineInformationLocalService;
	}

	/**
	 * Sets the baseline information local service.
	 *
	 * @param baselineInformationLocalService the baseline information local service
	 */
	public void setBaselineInformationLocalService(
		BaselineInformationLocalService baselineInformationLocalService) {
		this.baselineInformationLocalService = baselineInformationLocalService;
	}

	/**
	 * Returns the baseline information persistence.
	 *
	 * @return the baseline information persistence
	 */
	public BaselineInformationPersistence getBaselineInformationPersistence() {
		return baselineInformationPersistence;
	}

	/**
	 * Sets the baseline information persistence.
	 *
	 * @param baselineInformationPersistence the baseline information persistence
	 */
	public void setBaselineInformationPersistence(
		BaselineInformationPersistence baselineInformationPersistence) {
		this.baselineInformationPersistence = baselineInformationPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService getClassNameLocalService() {
		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService) {
		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {
		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		persistedModelLocalServiceRegistry.register("com.liferay.changeset.baseline.model.BaselineInformation",
			baselineInformationLocalService);
	}

	public void destroy() {
		persistedModelLocalServiceRegistry.unregister(
			"com.liferay.changeset.baseline.model.BaselineInformation");
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return BaselineInformationLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return BaselineInformation.class;
	}

	protected String getModelClassName() {
		return BaselineInformation.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = baselineInformationPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = com.liferay.changeset.baseline.service.BaselineEntryLocalService.class)
	protected com.liferay.changeset.baseline.service.BaselineEntryLocalService baselineEntryLocalService;
	@BeanReference(type = BaselineEntryPersistence.class)
	protected BaselineEntryPersistence baselineEntryPersistence;
	@BeanReference(type = BaselineInformationLocalService.class)
	protected BaselineInformationLocalService baselineInformationLocalService;
	@BeanReference(type = BaselineInformationPersistence.class)
	protected BaselineInformationPersistence baselineInformationPersistence;
	@ServiceReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameLocalService.class)
	protected com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService;
	@ServiceReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;
	@ServiceReference(type = com.liferay.portal.kernel.service.ResourceLocalService.class)
	protected com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserLocalService.class)
	protected com.liferay.portal.kernel.service.UserLocalService userLocalService;
	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	@ServiceReference(type = PersistedModelLocalServiceRegistry.class)
	protected PersistedModelLocalServiceRegistry persistedModelLocalServiceRegistry;
}