/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.changeset.baseline.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.AttachedModel;
import com.liferay.portal.kernel.model.AuditedModel;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the BaselineEntry service. Represents a row in the &quot;BaselineEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.changeset.baseline.model.impl.BaselineEntryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.changeset.baseline.model.impl.BaselineEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see BaselineEntry
 * @see com.liferay.changeset.baseline.model.impl.BaselineEntryImpl
 * @see com.liferay.changeset.baseline.model.impl.BaselineEntryModelImpl
 * @generated
 */
@ProviderType
public interface BaselineEntryModel extends AttachedModel, AuditedModel,
	BaseModel<BaselineEntry>, ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a baseline entry model instance should use the {@link BaselineEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this baseline entry.
	 *
	 * @return the primary key of this baseline entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this baseline entry.
	 *
	 * @param primaryKey the primary key of this baseline entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the baseline entry ID of this baseline entry.
	 *
	 * @return the baseline entry ID of this baseline entry
	 */
	public long getBaselineEntryId();

	/**
	 * Sets the baseline entry ID of this baseline entry.
	 *
	 * @param baselineEntryId the baseline entry ID of this baseline entry
	 */
	public void setBaselineEntryId(long baselineEntryId);

	/**
	 * Returns the company ID of this baseline entry.
	 *
	 * @return the company ID of this baseline entry
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this baseline entry.
	 *
	 * @param companyId the company ID of this baseline entry
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this baseline entry.
	 *
	 * @return the user ID of this baseline entry
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this baseline entry.
	 *
	 * @param userId the user ID of this baseline entry
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this baseline entry.
	 *
	 * @return the user uuid of this baseline entry
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this baseline entry.
	 *
	 * @param userUuid the user uuid of this baseline entry
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this baseline entry.
	 *
	 * @return the user name of this baseline entry
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this baseline entry.
	 *
	 * @param userName the user name of this baseline entry
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this baseline entry.
	 *
	 * @return the create date of this baseline entry
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this baseline entry.
	 *
	 * @param createDate the create date of this baseline entry
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this baseline entry.
	 *
	 * @return the modified date of this baseline entry
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this baseline entry.
	 *
	 * @param modifiedDate the modified date of this baseline entry
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the baseline information ID of this baseline entry.
	 *
	 * @return the baseline information ID of this baseline entry
	 */
	public long getBaselineInformationId();

	/**
	 * Sets the baseline information ID of this baseline entry.
	 *
	 * @param baselineInformationId the baseline information ID of this baseline entry
	 */
	public void setBaselineInformationId(long baselineInformationId);

	/**
	 * Returns the fully qualified class name of this baseline entry.
	 *
	 * @return the fully qualified class name of this baseline entry
	 */
	@Override
	public String getClassName();

	public void setClassName(String className);

	/**
	 * Returns the class name ID of this baseline entry.
	 *
	 * @return the class name ID of this baseline entry
	 */
	@Override
	public long getClassNameId();

	/**
	 * Sets the class name ID of this baseline entry.
	 *
	 * @param classNameId the class name ID of this baseline entry
	 */
	@Override
	public void setClassNameId(long classNameId);

	/**
	 * Returns the class pk of this baseline entry.
	 *
	 * @return the class pk of this baseline entry
	 */
	@Override
	public long getClassPK();

	/**
	 * Sets the class pk of this baseline entry.
	 *
	 * @param classPK the class pk of this baseline entry
	 */
	@Override
	public void setClassPK(long classPK);

	/**
	 * Returns the version of this baseline entry.
	 *
	 * @return the version of this baseline entry
	 */
	public double getVersion();

	/**
	 * Sets the version of this baseline entry.
	 *
	 * @param version the version of this baseline entry
	 */
	public void setVersion(double version);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(BaselineEntry baselineEntry);

	@Override
	public int hashCode();

	@Override
	public CacheModel<BaselineEntry> toCacheModel();

	@Override
	public BaselineEntry toEscapedModel();

	@Override
	public BaselineEntry toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}