/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.changeset.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.AuditedModel;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ChangesetBaselineCollection service. Represents a row in the &quot;ChangesetBaselineCollection&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.changeset.model.impl.ChangesetBaselineCollectionModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.changeset.model.impl.ChangesetBaselineCollectionImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ChangesetBaselineCollection
 * @see com.liferay.changeset.model.impl.ChangesetBaselineCollectionImpl
 * @see com.liferay.changeset.model.impl.ChangesetBaselineCollectionModelImpl
 * @generated
 */
@ProviderType
public interface ChangesetBaselineCollectionModel extends AuditedModel,
	BaseModel<ChangesetBaselineCollection>, ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a changeset baseline collection model instance should use the {@link ChangesetBaselineCollection} interface instead.
	 */

	/**
	 * Returns the primary key of this changeset baseline collection.
	 *
	 * @return the primary key of this changeset baseline collection
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this changeset baseline collection.
	 *
	 * @param primaryKey the primary key of this changeset baseline collection
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the changeset baseline collection ID of this changeset baseline collection.
	 *
	 * @return the changeset baseline collection ID of this changeset baseline collection
	 */
	public long getChangesetBaselineCollectionId();

	/**
	 * Sets the changeset baseline collection ID of this changeset baseline collection.
	 *
	 * @param changesetBaselineCollectionId the changeset baseline collection ID of this changeset baseline collection
	 */
	public void setChangesetBaselineCollectionId(
		long changesetBaselineCollectionId);

	/**
	 * Returns the company ID of this changeset baseline collection.
	 *
	 * @return the company ID of this changeset baseline collection
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this changeset baseline collection.
	 *
	 * @param companyId the company ID of this changeset baseline collection
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this changeset baseline collection.
	 *
	 * @return the user ID of this changeset baseline collection
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this changeset baseline collection.
	 *
	 * @param userId the user ID of this changeset baseline collection
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this changeset baseline collection.
	 *
	 * @return the user uuid of this changeset baseline collection
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this changeset baseline collection.
	 *
	 * @param userUuid the user uuid of this changeset baseline collection
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this changeset baseline collection.
	 *
	 * @return the user name of this changeset baseline collection
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this changeset baseline collection.
	 *
	 * @param userName the user name of this changeset baseline collection
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this changeset baseline collection.
	 *
	 * @return the create date of this changeset baseline collection
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this changeset baseline collection.
	 *
	 * @param createDate the create date of this changeset baseline collection
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this changeset baseline collection.
	 *
	 * @return the modified date of this changeset baseline collection
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this changeset baseline collection.
	 *
	 * @param modifiedDate the modified date of this changeset baseline collection
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this changeset baseline collection.
	 *
	 * @return the name of this changeset baseline collection
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this changeset baseline collection.
	 *
	 * @param name the name of this changeset baseline collection
	 */
	public void setName(String name);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		ChangesetBaselineCollection changesetBaselineCollection);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ChangesetBaselineCollection> toCacheModel();

	@Override
	public ChangesetBaselineCollection toEscapedModel();

	@Override
	public ChangesetBaselineCollection toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}