/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.changeset.baseline.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.changeset.baseline.model.BaselineEntry;
import com.liferay.changeset.baseline.service.BaselineEntryLocalServiceUtil;

/**
 * The extended model base implementation for the BaselineEntry service. Represents a row in the &quot;BaselineEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link BaselineEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see BaselineEntryImpl
 * @see BaselineEntry
 * @generated
 */
@ProviderType
public abstract class BaselineEntryBaseImpl extends BaselineEntryModelImpl
	implements BaselineEntry {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a baseline entry model instance should use the {@link BaselineEntry} interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			BaselineEntryLocalServiceUtil.addBaselineEntry(this);
		}
		else {
			BaselineEntryLocalServiceUtil.updateBaselineEntry(this);
		}
	}
}